<Project>

  <PropertyGroup>
    <RootNamespace>Hj.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <LangVersion>Latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Henrik Jensen</Authors>
    <Copyright>Copyright 2026 Henrik Jensen</Copyright>
  </PropertyGroup>

</Project>
